### ISSUE TITLE
[Enhancement] - Recaptcha

### ISSUE THREAD

**Issue by pautiina** [respawner/looking-glass#30]
will be good add Recaptcha Google  after 5-use comand/

**Comment by respawner** [comment]
Interesting idea.

The first issue to address is the fact that we don't have any data persistence. What I mean is that there is no way for now to tell if the last _n_ commands have been requested by the same user.

The global idea is to have some kind of anti-spam system to avoid potential threads.

I'd like to avoid as much as possible dependencies. I thought at the beginning to code an anti-spam feature using an SQLite database to have some data persistence. Maybe we need to re-evaluate this.

Also, we will of course need a configuration option to enable/disable this anti-spam feature.

**Comment by User4574** [comment]
What would be the concern with having it recaptcha you every time? It would avoid the need for data persistence. If you use the invisible recaptcha the user would likely not notice any difference. 

Alternatively, introducing data persistence offers other options, such as command history and rate limiting which would both be good features.

**Comment by respawner** [comment]
@User4574 I agree with both of your two points.

But for now I would go for the first one (invisible recaptcha every time). That would probably the quickest and easiest way to go.

Introducing data persistence means mostly introducing a database which I rather not do for now, at least for the 2.X.Y versions series.

**Comment by labrack** [comment]
[modifications.txt](https://github.com/respawner/looking-glass/files/1695398/modifications.txt)
When we tried to overcome the abuse issue, recaptcha was considered, but we also wanted request logging, so we wound up making a mysql backend and logging all the attempts. Seemed to work out great, but it does utilize a db (which is why I haven't issued a PR, knowing @respawner doesn't want to introduce a DB at this time). See our modifications attached, in case anyone is currently trying to overcome this as well. 

Here's our security flow:
![lg-security-flow](https://user-images.githubusercontent.com/5885484/35808748-c7d4ee04-0a54-11e8-9989-3abe1e37ae96.png)

The code goes just before the "// Do the processing" line in execute.php.
[modifications.txt](https://github.com/respawner/looking-glass/files/1695404/modifications.txt)
